name: Send Email
on:
  push:
    branches:
      - main

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          # SMTP Configuration
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          
          # Email details
          subject: "📌 New Commit to Main"
          to: ErfanMelon@outlook.com,Alireza3205@gmail.com
          from: PhoneixTaskApi
          content_type: text/plain
          body: |
            🚀 A new commit was pushed to the main branch! 🎉

            📂 Repository: ${{ github.repository }}
            ✉️ Commit Message: ${{ github.event.head_commit.message }}
            👤 Author: ${{ github.event.head_commit.author.name }}
            🔑 Commit SHA: ${{ github.sha }}
            🔍 Compare Changes: ${{ github.event.compare }}
            ⏰ Timestamp: ${{ github.event.head_commit.timestamp }}

            🌟 Happy coding! 
            🔄 Triggered automatically by GitHub Actions
