name: Send Email
on:
  push:
    branches:
      - main

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          # SMTP Configuration (using Gmail as example)
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          
          # Email details
          subject: "🚀 New Commit to Main: ${{ github.event.head_commit.message }}"
          to: ErfanMelon@outlook.com
          from: PhoneixTaskApi  # Sets sender name
          content_type: text/html  # Enables HTML formatting
          body: |
            <h3>A new commit was pushed to the <code>main</code> branch:</h3>
            <p><strong>Repository:</strong> ${{ github.repository }}</p>
            <p><strong>Commit Message:</strong> ${{ github.event.head_commit.message }}</p>
            <p><strong>Author:</strong> ${{ github.event.head_commit.author.name }}</p>
            <p><strong>Commit SHA:</strong> <code>${{ github.sha }}</code></p>
            <p><strong>Compare Changes:</strong> <a href="${{ github.event.compare }}">View Diff</a></p>
            <hr>
            <p>Triggered by GitHub Actions at ${{ github.event.head_commit.timestamp }}</p>
